name: mypy

on: [push, workflow_dispatch]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3
      - name: actions/install
        uses: ./.github/actions/install
      - run: pip3 install mypy
      - run: python3 -m mypy dmba
