name: pytest

on: [push, workflow_dispatch]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v3
      - name: actions/install
        uses: ./.github/actions/install
      - run: sudo apt install -y graphviz
      - name: pip3-install
      - run: pip3 install pytest
      - run: python3 -m pytest -p no:cacheprovider
