name: ruff

on: [push, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3
      - name: .github/actions/install
        uses: ./.github/actions/install
      - run: pip3 install ruff
      - name: ruff
        run: | 
          python3 -m ruff dmba
