name: ruff

on: [push, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3
      - name: actions/install
        uses: ./.github/actions/install
      - name: ruff
        run: |
          pip3 install ruff 
          python3 -m ruff dmba
